# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}}" \
    --robot.id=black \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    --display_data=true
    # <- Optional: specify video codec (h264, hevc, libsvtav1). Default is libsvtav1. \
    # --dataset.vcodec=h264 \
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so_follower \
  --robot.left_arm_config.port=/dev/tty.usbmodem5A460822851 \
  --robot.right_arm_config.port=/dev/tty.usbmodem5A460814411 \
  --robot.id=bimanual_follower \
  --robot.left_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 3, "width": 640, "height": 480, "fps": 30},
  }' --robot.right_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30},
    front: {"type": "opencv", "index_or_path": 4, "width": 640, "height": 480, "fps": 30},
  }' \
  --teleop.type=bi_so_leader \
  --teleop.left_arm_config.port=/dev/tty.usbmodem5A460852721 \
  --teleop.right_arm_config.port=/dev/tty.usbmodem5A460819811 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm"
```
"""

from copy import copy, deepcopy
import logging
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat
from typing import Any

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.reachy2_camera.configuration_reachy2_camera import Reachy2CameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.cameras.zmq.configuration_zmq import ZMQCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.pipeline_features import aggregate_pipeline_dataset_features, create_initial_features
from lerobot.datasets.utils import combine_feature_dicts
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.processor import make_default_processors
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import (  # noqa: F401
    RobotConfig,
    bi_openarm_follower,
    bi_piper_follower,
    bi_so_follower,
    earthrover_mini_plus,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    omx_follower,
    openarm_follower,
    piper_follower,
    reachy2,
    so_follower,
    unitree_g1 as unitree_g1_robot,
)
from lerobot.scripts.recording_hil import (
    ACPInferenceConfig,
    PolicySyncDualArmExecutor,
    _capture_policy_runtime_state,  # noqa: F401
    _predict_policy_action_with_acp_inference,  # noqa: F401
)
from lerobot.scripts.recording_ee_pose import (
    PiperEEPoseStorage,
    replace_low_dim_features_with_piper_ee_pose,
)
from lerobot.scripts.ee_pose_action_utils import (
    ACTION_SCHEMA_NAMES,
    BIMANUAL_EE_RPY_NAMES,
    MapPolicyQuatActionToRPYStep,
    MapPolicyRPYActionToIKTargetsStep,
    MapPolicyRXRYRZActionToRPYStep,
    SDK_EE_OFFSET_XYZRPY,
    bimanual_ee_quat_to_rpy_values,
    detect_action_schema_from_names,
)
from lerobot.scripts.recording_loop import record_loop
from lerobot.teleoperators import (  # noqa: F401
    TeleoperatorConfig,
    bi_openarm_leader,
    bi_piper_leader,
    bi_so_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    omx_leader,
    openarm_leader,
    piper_leader,
    reachy2_teleoperator,
    so_leader,
    unitree_g1,
)
from lerobot.teleoperators.bi_quest3_vr.config_bi_quest3_vr import BiQuest3VRTeleopConfig  # noqa: F401
from lerobot.teleoperators.quest3_vr.config_quest3_vr import Quest3VRTeleopConfig  # noqa: F401
from lerobot.teleoperators.quest3_vr.processors import (
    make_bi_quest3_vr_robot_action_processor_from_config,
    make_quest3_vr_robot_action_processor_from_config,
)
from lerobot.utils.constants import ACTION, OBS_STATE
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    sanity_check_bimanual_piper_pair,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.import_utils import register_third_party_plugins
from lerobot.utils.recording_annotations import (
    infer_collector_policy_id,
    normalize_episode_success_label,
    resolve_episode_success_label,
)
from lerobot.utils.utils import (
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # Video codec for encoding videos. Options: 'h264', 'hevc', 'libsvtav1'.
    # Use 'h264' for faster encoding on systems where AV1 encoding is CPU-heavy.
    vcodec: str = "libsvtav1"
    # Rename map for the observation to override the image and state keys
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Display data on a remote Rerun server
    display_ip: str | None = None
    # Port of the remote Rerun server
    display_port: int | None = None
    # Whether to  display compressed images in Rerun
    display_compressed_images: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False
    # In policy mode, broadcast the same robot action to the teleop arm via `teleop.send_feedback`.
    policy_sync_to_teleop: bool = False
    # Use parallel dispatch to reduce action broadcast latency when syncing policy to teleop.
    policy_sync_parallel: bool = True
    # Enable S0/S1/S2 intervention state machine when policy + teleop are both available.
    intervention_state_machine_enabled: bool = True
    # Keyboard key used to toggle entering/leaving intervention.
    intervention_toggle_key: str = "i"
    # Whether to capture episode-level success/failure labels from keyboard.
    enable_episode_outcome_labeling: bool = False
    # Keyboard key to mark the current episode as success and end it.
    episode_success_key: str = "s"
    # Keyboard key to mark the current episode as failure and end it.
    episode_failure_key: str = "f"
    # Optional fallback label used when no explicit success/failure key was pressed.
    default_episode_success: str | None = None
    # If True, require explicit or default episode labels before saving.
    require_episode_success_label: bool = False
    # Whether to store step-level collector policy provenance.
    enable_collector_policy_id: bool = False
    # Policy identifier used when action source is policy. If omitted, inferred from policy config.
    collector_policy_id_policy: str | None = None
    # Policy identifier used when action source is human/teleop.
    collector_policy_id_human: str = "human"
    # ACP inference controls for policy-driven recording.
    acp_inference: ACPInferenceConfig = field(default_factory=ACPInferenceConfig)
    # Retry timeout for transient communication errors (seconds). Set to 0 to fail immediately.
    communication_retry_timeout_s: float = 2.0
    # Sleep interval between communication retries (seconds).
    communication_retry_interval_s: float = 0.1
    # Store low-dimensional Piper state/action as SDK end-effector pose feedback instead of joint positions.
    record_ee_pose: bool = False
    # Policy action schema used when `record_ee_pose=true`.
    policy_action_schema: str = "bimanual_ee_quat"
    # Treat a bimanual EE-pose policy arm as stationary when its per-frame action delta is at or below this.
    policy_stationary_arm_delta_threshold: float = 1e-5

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")

        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")

            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        if self.teleop is None and self.policy is None:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")
        sanity_check_bimanual_piper_pair(self.robot, self.teleop)
        if not self.intervention_toggle_key or len(self.intervention_toggle_key) != 1:
            raise ValueError("`intervention_toggle_key` must be a single character.")

        if self.enable_episode_outcome_labeling:
            label_key_bindings = {
                "episode_success_key": self.episode_success_key,
                "episode_failure_key": self.episode_failure_key,
            }
            for key_name, key_value in label_key_bindings.items():
                if not key_value or len(key_value) != 1:
                    raise ValueError(f"`{key_name}` must be a single character.")

            normalized_keys = [
                self.intervention_toggle_key.lower(),
                self.episode_success_key.lower(),
                self.episode_failure_key.lower(),
            ]
            if len(set(normalized_keys)) != len(normalized_keys):
                raise ValueError(
                    "`intervention_toggle_key`, `episode_success_key`, and `episode_failure_key` must be distinct."
                )

        if self.default_episode_success is not None:
            self.default_episode_success = normalize_episode_success_label(self.default_episode_success)

        if not self.collector_policy_id_human:
            raise ValueError("`collector_policy_id_human` must be a non-empty string.")
        if self.acp_inference.use_cfg and not self.acp_inference.enable:
            raise ValueError("`acp_inference.use_cfg=true` requires `acp_inference.enable=true`.")
        if self.acp_inference.cfg_beta < 0:
            raise ValueError("`acp_inference.cfg_beta` must be >= 0.")
        if self.communication_retry_timeout_s < 0:
            raise ValueError("`communication_retry_timeout_s` must be >= 0.")
        if self.communication_retry_interval_s <= 0:
            raise ValueError("`communication_retry_interval_s` must be > 0.")
        if self.policy_stationary_arm_delta_threshold < 0:
            raise ValueError("`policy_stationary_arm_delta_threshold` must be >= 0.")
        if self.record_ee_pose and self.policy_action_schema not in {"bimanual_ee_quat", "bimanual_ee_rpy"}:
            raise ValueError(
                "`record_ee_pose=true` requires `policy_action_schema` to be one of "
                "['bimanual_ee_quat', 'bimanual_ee_rpy']."
            )

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


def _ensure_human_inloop_compatible_features(
    dataset_features: dict[str, dict],
    *,
    action_feature_names: list[str],
) -> None:
    # Keep human-in-loop datasets schema-stable across teleop-only and policy-assisted phases so they can merge.
    dataset_features["complementary_info.policy_action"] = {
        "dtype": "float32",
        "shape": (len(action_feature_names),),
        "names": action_feature_names,
    }
    dataset_features["complementary_info.is_intervention"] = {
        "dtype": "float32",
        "shape": (1,),
        "names": ["is_intervention"],
    }
    dataset_features["complementary_info.state"] = {
        "dtype": "float32",
        "shape": (1,),
        "names": ["state"],
    }


def _policy_action_dim(cfg: PreTrainedConfig | None) -> int | None:
    if cfg is None or cfg.action_feature is None:
        return None
    shape = cfg.action_feature.shape
    if not shape:
        return None
    return int(shape[0])


def _metadata_with_features(meta: Any, features: dict[str, dict]) -> Any:
    meta_copy = copy(meta)
    meta_copy.info = deepcopy(meta.info)
    meta_copy.info["features"] = features
    return meta_copy


def _policy_features_with_action_names(
    features: dict[str, dict],
    action_names: tuple[str, ...],
    observation_state_names: tuple[str, ...] | None = None,
) -> dict[str, dict]:
    policy_features = deepcopy(features)
    if ACTION in policy_features:
        policy_features[ACTION] = {
            **policy_features[ACTION],
            "shape": (len(action_names),),
            "names": list(action_names),
        }
    if observation_state_names is not None and OBS_STATE in policy_features:
        policy_features[OBS_STATE] = {
            **policy_features[OBS_STATE],
            "shape": (len(observation_state_names),),
            "names": list(observation_state_names),
        }
    return policy_features


def _bimanual_ee_rpy_policy_observation(values: dict[str, Any]) -> dict[str, Any]:
    return {**values, **bimanual_ee_quat_to_rpy_values(values)}


def _set_policy_action_schema(features: dict[str, dict], action_names: tuple[str, ...]) -> None:
    if "complementary_info.policy_action" in features:
        features["complementary_info.policy_action"] = {
            **features["complementary_info.policy_action"],
            "shape": (len(action_names),),
            "names": list(action_names),
        }


def _auto_policy_action_names_for_ee_pose(robot: Any, ee_pose_format: str) -> tuple[str, ...]:
    if ee_pose_format == "rpy":
        if hasattr(robot, "left_arm") and hasattr(robot, "right_arm"):
            return ACTION_SCHEMA_NAMES["bimanual_ee_rpy"]
        return ACTION_SCHEMA_NAMES["single_ee_rpy"]
    if ee_pose_format == "quat":
        if hasattr(robot, "left_arm") and hasattr(robot, "right_arm"):
            return ACTION_SCHEMA_NAMES["bimanual_ee_quat"]
        return ACTION_SCHEMA_NAMES["single_ee_quat"]
    raise ValueError(f"Unsupported EE pose format: {ee_pose_format!r}.")


def _ensure_ee_policy_schema_matches_storage(
    *,
    policy_action_schema: str,
    policy_action_names: tuple[str, ...],
    robot: Any,
    ee_pose_format: str,
) -> None:
    expected_names = _auto_policy_action_names_for_ee_pose(robot, ee_pose_format)
    if policy_action_names != expected_names:
        raise ValueError(
            f"`record_ee_pose=true` with `{ee_pose_format}` storage requires the EE policy action schema "
            f"to match {list(expected_names)}, got schema={policy_action_schema!r} "
            f"names={list(policy_action_names)}."
        )


@dataclass(frozen=True)
class _PolicyActionDescriptor:
    source: str
    schema: str
    action_names: tuple[str, ...]


def _resolve_policy_action_descriptor(cfg: Any, control_features: dict[str, dict]) -> _PolicyActionDescriptor:
    if getattr(cfg, "policy", None) is None:
        return _PolicyActionDescriptor(source="unknown", schema="unknown", action_names=())

    action_names = getattr(cfg, "policy_action_names", None)
    if action_names is None:
        schema = getattr(cfg, "policy_action_schema", None)
        if schema in ACTION_SCHEMA_NAMES:
            action_names = ACTION_SCHEMA_NAMES[schema]
        else:
            return _PolicyActionDescriptor(source="policy", schema="unknown", action_names=())

    joint_names = tuple(control_features[ACTION]["names"])
    resolved_schema = detect_action_schema_from_names(tuple(action_names), joint_names)
    if resolved_schema == "unknown":
        raise ValueError(f"Unable to resolve `policy_action_names`: {list(action_names)}.")
    return _PolicyActionDescriptor(
        source="policy",
        schema=resolved_schema,
        action_names=tuple(action_names),
    )


def _make_policy_action_processor_for_ee_pose(cfg: RecordConfig) -> Any | None:
    if cfg.teleop is None:
        return None
    if cfg.teleop.type == "quest3_vr":
        teleop_cfg = copy(cfg.teleop)
        teleop_cfg.piper_ee_offset_xyzrpy = SDK_EE_OFFSET_XYZRPY
        return make_quest3_vr_robot_action_processor_from_config(teleop_cfg)
    if cfg.teleop.type == "bi_quest3_vr":
        teleop_cfg = copy(cfg.teleop)
        teleop_cfg.piper_ee_offset_xyzrpy = SDK_EE_OFFSET_XYZRPY
        return make_bi_quest3_vr_robot_action_processor_from_config(teleop_cfg)
    return None


def _compose_policy_action_processor(steps: list[Any], ik_processor: Any) -> Any:
    return type(ik_processor)(
        steps=[*steps, *ik_processor.steps],
        to_transition=ik_processor.to_transition,
        to_output=ik_processor.to_output,
    )


def _make_policy_action_processor_for_rpy_schema(action_names: tuple[str, ...], robot: Any) -> Any:
    if tuple(action_names) == BIMANUAL_EE_RPY_NAMES:
        if not (
            hasattr(robot, "left_arm")
            and hasattr(robot, "right_arm")
            or getattr(robot, "name", None) in {"bi_piper_follower", "bi_piper_x_follower"}
        ):
            raise ValueError("bimanual_ee_rpy policy actions require a bimanual Piper/PiperX follower robot.")
        ik_processor = make_bi_quest3_vr_robot_action_processor_from_config(
            BiQuest3VRTeleopConfig(piper_ee_offset_xyzrpy=SDK_EE_OFFSET_XYZRPY)
        )
        return _compose_policy_action_processor(
            [MapPolicyRPYActionToIKTargetsStep(bimanual=True)], ik_processor
        )

    if tuple(action_names) == ACTION_SCHEMA_NAMES["single_ee_rpy"]:
        if getattr(robot, "name", None) not in {"piper_follower", "piper_x_follower"}:
            raise ValueError("single_ee_rpy policy actions require a single-arm Piper/PiperX follower robot.")
        ik_processor = make_quest3_vr_robot_action_processor_from_config(
            Quest3VRTeleopConfig(piper_ee_offset_xyzrpy=SDK_EE_OFFSET_XYZRPY)
        )
        return _compose_policy_action_processor([MapPolicyRPYActionToIKTargetsStep()], ik_processor)

    raise ValueError(f"Unsupported RPY policy action names: {list(action_names)}.")


def _make_policy_action_processor_for_ee_schema(
    policy_action_schema: str,
    policy_action_names: tuple[str, ...],
    robot: Any,
    cfg: RecordConfig,
) -> Any | None:
    if policy_action_schema == "joint":
        return None
    if policy_action_schema == "bimanual_ee_quat":
        return _make_policy_action_processor_for_ee_pose(cfg)
    if policy_action_schema == "bimanual_ee_rpy":
        return _make_policy_action_processor_for_rpy_schema(policy_action_names, robot)
    if policy_action_schema == "single_ee_rxryrz":
        ik_processor = make_quest3_vr_robot_action_processor_from_config(
            Quest3VRTeleopConfig(piper_ee_offset_xyzrpy=SDK_EE_OFFSET_XYZRPY)
        )
        return _compose_policy_action_processor(
            [MapPolicyRXRYRZActionToRPYStep(), MapPolicyRPYActionToIKTargetsStep()], ik_processor
        )
    if policy_action_schema == "single_ee_quat":
        ik_processor = make_quest3_vr_robot_action_processor_from_config(
            Quest3VRTeleopConfig(piper_ee_offset_xyzrpy=SDK_EE_OFFSET_XYZRPY)
        )
        return _compose_policy_action_processor(
            [MapPolicyQuatActionToRPYStep(), MapPolicyRPYActionToIKTargetsStep()], ik_processor
        )
    raise ValueError(f"Unsupported policy action schema: {policy_action_schema!r}.")


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    if cfg.require_episode_success_label and not cfg.enable_episode_outcome_labeling:
        raise ValueError(
            "`require_episode_success_label=true` requires `enable_episode_outcome_labeling=true`."
        )
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording", ip=cfg.display_ip, port=cfg.display_port)
    display_compressed_images = (
        True
        if (cfg.display_data and cfg.display_ip is not None and cfg.display_port is not None)
        else cfg.display_compressed_images
    )

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    teleop_action_processor, robot_action_processor, robot_observation_processor = make_default_processors()
    if cfg.teleop is not None and cfg.teleop.type == "quest3_vr":
        teleop_action_processor = make_quest3_vr_robot_action_processor_from_config(cfg.teleop)
    elif cfg.teleop is not None and cfg.teleop.type == "bi_quest3_vr":
        teleop_action_processor = make_bi_quest3_vr_robot_action_processor_from_config(cfg.teleop)

    dataset_features = combine_feature_dicts(
        aggregate_pipeline_dataset_features(
            pipeline=teleop_action_processor,
            initial_features=create_initial_features(
                action=robot.action_features
            ),  # TODO(steven, pepijn): in future this should be come from teleop or policy
            use_videos=cfg.dataset.video,
        ),
        aggregate_pipeline_dataset_features(
            pipeline=robot_observation_processor,
            initial_features=create_initial_features(observation=robot.observation_features),
            use_videos=cfg.dataset.video,
        ),
    )
    control_features = deepcopy(dataset_features)
    if cfg.teleop is not None:
        action_names = dataset_features[ACTION]["names"]
        action_names = list(robot.action_features) if action_names is None else list(action_names)
        _ensure_human_inloop_compatible_features(dataset_features, action_feature_names=action_names)
        _ensure_human_inloop_compatible_features(control_features, action_feature_names=action_names)
    if cfg.enable_collector_policy_id:
        dataset_features["complementary_info.collector_policy_id"] = {
            "dtype": "string",
            "shape": (1,),
            "names": ["collector_policy_id"],
        }
        control_features["complementary_info.collector_policy_id"] = {
            "dtype": "string",
            "shape": (1,),
            "names": ["collector_policy_id"],
        }

    if cfg.record_ee_pose:
        replace_low_dim_features_with_piper_ee_pose(dataset_features, robot)
        if cfg.policy_action_schema == "bimanual_ee_rpy":
            _set_policy_action_schema(dataset_features, BIMANUAL_EE_RPY_NAMES)
        logging.info(
            "`record_ee_pose=true`: dataset low-dimensional state/action will be stored as Piper SDK "
            "end-effector feedback pose. Robot control still uses joint actions."
        )

    dataset = None
    listener = None
    policy_sync_executor = None
    policy_action_processor = None
    policy_observation_transform = None
    ee_pose_storage = PiperEEPoseStorage(robot) if cfg.record_ee_pose else None

    try:
        if cfg.resume:
            dataset = LeRobotDataset(
                cfg.dataset.repo_id,
                root=cfg.dataset.root,
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
            )

            if hasattr(robot, "cameras") and len(robot.cameras) > 0:
                dataset.start_image_writer(
                    num_processes=cfg.dataset.num_image_writer_processes,
                    num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                )
            sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
        else:
            # Create empty dataset or load existing saved episodes
            sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
            dataset = LeRobotDataset.create(
                cfg.dataset.repo_id,
                cfg.dataset.fps,
                root=cfg.dataset.root,
                robot_type=robot.name,
                features=dataset_features,
                use_videos=cfg.dataset.video,
                image_writer_processes=cfg.dataset.num_image_writer_processes,
                image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
            )

        # Load pretrained policy. When EE-pose storage is enabled, support both legacy joint-space
        # policies and newer EE-pose policies. EE-pose policy outputs are adapted to Piper joint
        # commands by an independent policy action processor before they reach robot.send_action().
        policy_ds_meta = dataset.meta
        policy_features = dataset.meta.features
        if cfg.record_ee_pose:
            action_dim = _policy_action_dim(cfg.policy)

            if cfg.policy is None or action_dim is None:
                policy_ds_meta = _metadata_with_features(dataset.meta, control_features)
                policy_features = control_features
            else:
                if cfg.policy_action_schema not in {"bimanual_ee_quat", "bimanual_ee_rpy"}:
                    raise ValueError(
                        "`record_ee_pose=true` policy execution only supports "
                        "`policy_action_schema=bimanual_ee_quat` or `bimanual_ee_rpy`."
                    )
                policy_action_names = ACTION_SCHEMA_NAMES[cfg.policy_action_schema]
                if action_dim != len(policy_action_names):
                    raise ValueError(
                        "`record_ee_pose=true` policy action shape is incompatible with "
                        f"`policy_action_schema={cfg.policy_action_schema}`. Got action_dim={action_dim}, "
                        f"expected {len(policy_action_names)}."
                    )
                policy_observation_names = (
                    BIMANUAL_EE_RPY_NAMES if cfg.policy_action_schema == "bimanual_ee_rpy" else None
                )
                policy_features = _policy_features_with_action_names(
                    dataset.meta.features,
                    policy_action_names,
                    observation_state_names=policy_observation_names,
                )
                _set_policy_action_schema(policy_features, policy_action_names)
                if cfg.policy_action_schema == "bimanual_ee_rpy":
                    policy_observation_transform = _bimanual_ee_rpy_policy_observation
                policy_ds_meta = _metadata_with_features(dataset.meta, policy_features)
                policy_action_processor = _make_policy_action_processor_for_ee_schema(
                    cfg.policy_action_schema, policy_action_names, robot, cfg
                )
                if policy_action_processor is None:
                    raise ValueError(
                        "`record_ee_pose=true` detected an EE-pose policy action schema, but no Piper "
                        f"EE action adapter is available for schema '{cfg.policy_action_schema}'."
                    )
                logging.info(
                    "`record_ee_pose=true`: policy_action_schema=%s action_dim=%d; "
                    "policy outputs will be adapted through EE->joint IK before robot execution.",
                    cfg.policy_action_schema,
                    action_dim,
                )

        policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=policy_ds_meta)
        preprocessor = None
        postprocessor = None
        if cfg.acp_inference.enable and cfg.policy is None:
            raise ValueError("`acp_inference.enable=true` requires `policy` to be set.")
        if cfg.policy is not None:
            preprocessor, postprocessor = make_pre_post_processors(
                policy_cfg=cfg.policy,
                pretrained_path=cfg.policy.pretrained_path,
                dataset_stats=rename_stats(policy_ds_meta.stats, cfg.dataset.rename_map),
                preprocessor_overrides={
                    "device_processor": {"device": cfg.policy.device},
                    "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
                },
            )

        collector_policy_id_policy = (
            cfg.collector_policy_id_policy
            if cfg.collector_policy_id_policy is not None
            else infer_collector_policy_id(cfg.policy)
        )
        collector_policy_id_human = cfg.collector_policy_id_human

        robot.connect()
        if teleop is not None:
            teleop.connect()
        on_record_connected = getattr(cfg, "_on_record_connected", None)
        if callable(on_record_connected):
            on_record_connected(robot, teleop)

        if cfg.policy_sync_to_teleop:
            if cfg.policy is None:
                raise ValueError("`policy_sync_to_teleop=true` requires `policy` to be set.")
            if teleop is None or isinstance(teleop, list):
                raise ValueError(
                    "`policy_sync_to_teleop=true` requires exactly one teleoperator with send_feedback support."
                )
            policy_sync_executor = PolicySyncDualArmExecutor(
                robot=robot,
                teleop=teleop,
                parallel_dispatch=cfg.policy_sync_parallel,
            )

        listener, events = init_keyboard_listener(
            intervention_toggle_key=cfg.intervention_toggle_key,
            episode_success_key=cfg.episode_success_key if cfg.enable_episode_outcome_labeling else None,
            episode_failure_key=cfg.episode_failure_key if cfg.enable_episode_outcome_labeling else None,
        )

        with VideoEncodingManager(dataset):
            recorded_episodes = 0
            while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
                events["episode_outcome"] = None
                log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop_action_processor=teleop_action_processor,
                    robot_action_processor=robot_action_processor,
                    robot_observation_processor=robot_observation_processor,
                    teleop=teleop,
                    policy=policy,
                    preprocessor=preprocessor,
                    postprocessor=postprocessor,
                    policy_action_processor=policy_action_processor,
                    dataset=dataset,
                    control_time_s=cfg.dataset.episode_time_s,
                    single_task=cfg.dataset.single_task,
                    display_data=cfg.display_data,
                    display_compressed_images=display_compressed_images,
                    policy_sync_executor=policy_sync_executor,
                    intervention_state_machine_enabled=cfg.intervention_state_machine_enabled,
                    collector_policy_id_policy=collector_policy_id_policy,
                    collector_policy_id_human=collector_policy_id_human,
                    acp_inference=cfg.acp_inference,
                    communication_retry_timeout_s=cfg.communication_retry_timeout_s,
                    communication_retry_interval_s=cfg.communication_retry_interval_s,
                    control_features=control_features if cfg.record_ee_pose else None,
                    policy_features=policy_features,
                    policy_observation_transform=policy_observation_transform,
                    ee_pose_storage=ee_pose_storage,
                    policy_stationary_arm_delta_threshold=cfg.policy_stationary_arm_delta_threshold,
                )

                episode_success = None
                if cfg.enable_episode_outcome_labeling:
                    episode_success = resolve_episode_success_label(
                        explicit_label=events.get("episode_outcome"),
                        default_label=cfg.default_episode_success,
                        require_label=cfg.require_episode_success_label,
                    )
                    if events.get("episode_outcome") is None and episode_success is not None:
                        logging.warning(
                            "Episode %s has no explicit success/failure label, defaulting to '%s'.",
                            dataset.num_episodes,
                            episode_success,
                        )

                on_episode_outcome = getattr(cfg, "_on_record_episode_outcome", None)
                if callable(on_episode_outcome):
                    on_episode_outcome(robot, teleop, episode_success)

                prepare_episode_reset = getattr(teleop, "prepare_episode_reset", None)
                prepare_episode_start = getattr(teleop, "prepare_episode_start", None)
                has_episode_reset_hook = callable(prepare_episode_reset)

                # Execute without recording to reset the environment. Quest3-style teleops can request
                # this after every episode so the next one starts from a clean initial pose.
                should_reset_between_episodes = (recorded_episodes < cfg.dataset.num_episodes - 1) or events[
                    "rerecord_episode"
                ]
                if not events["stop_recording"] and (should_reset_between_episodes or has_episode_reset_hook):
                    log_say("Reset the environment", cfg.play_sounds)

                    # reset g1 robot
                    if robot.name == "unitree_g1":
                        robot.reset()

                    if has_episode_reset_hook:
                        prepare_episode_reset()

                    reset_time_s = cfg.dataset.reset_time_s
                    reset_interp_steps = int(getattr(cfg.teleop, "reset_interp_steps", 0) or 0)
                    if has_episode_reset_hook and reset_interp_steps > 0:
                        reset_time_s = max(reset_time_s, (reset_interp_steps + 1) / cfg.dataset.fps)

                    record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop_action_processor=teleop_action_processor,
                        robot_action_processor=robot_action_processor,
                        robot_observation_processor=robot_observation_processor,
                        teleop=teleop,
                        control_time_s=reset_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                        policy_sync_executor=policy_sync_executor,
                        intervention_state_machine_enabled=cfg.intervention_state_machine_enabled,
                        collector_policy_id_policy=collector_policy_id_policy,
                        collector_policy_id_human=collector_policy_id_human,
                        acp_inference=cfg.acp_inference,
                        communication_retry_timeout_s=cfg.communication_retry_timeout_s,
                        communication_retry_interval_s=cfg.communication_retry_interval_s,
                        control_features=control_features if cfg.record_ee_pose else None,
                        policy_features=policy_features,
                        policy_observation_transform=policy_observation_transform,
                        ee_pose_storage=ee_pose_storage,
                        policy_stationary_arm_delta_threshold=cfg.policy_stationary_arm_delta_threshold,
                    )

                    if callable(prepare_episode_start):
                        prepare_episode_start()
                    if has_episode_reset_hook:
                        teleop_action_processor.reset()

                if events["rerecord_episode"]:
                    log_say("Re-record episode", cfg.play_sounds)
                    events["rerecord_episode"] = False
                    events["exit_early"] = False
                    events["episode_outcome"] = None
                    dataset.clear_episode_buffer()
                    continue

                extra_episode_metadata = (
                    {"episode_success": episode_success} if cfg.enable_episode_outcome_labeling else None
                )
                dataset.save_episode(extra_episode_metadata=extra_episode_metadata)
                recorded_episodes += 1
    finally:
        log_say("Stop recording", cfg.play_sounds, blocking=True)

        if dataset:
            dataset.finalize()

        if policy_sync_executor is not None:
            policy_sync_executor.shutdown()

        if robot.is_connected:
            robot.disconnect()
        if teleop and teleop.is_connected:
            teleop.disconnect()

        if listener and hasattr(listener, "stop"):
            listener.stop()

        if cfg.dataset.push_to_hub:
            if dataset is not None:
                dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)
            else:
                logging.warning(
                    "`dataset.push_to_hub=true` was requested, but dataset was not initialized due to an earlier error."
                )

        log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    register_third_party_plugins()
    record()


if __name__ == "__main__":
    main()
